Add backend for bookable office hours
pennlabs/office-hours-queue pull request #324
Opened 2024-11-18 15:41 UTC by dkwncho

- Created new Booking model, serializer, permission, urls, and viewset

Note: These changes will not be fully functional until the Occurrence model in schedule.models is updated (pull request is open in the django-schedules repository with those minor changes)

2024-11-19 05:10 UTC, benjmnxu requested changes
I think there is an issue with the Booking creation logic–please read my comment on it. Otherwise, I think we're pretty close to getting this merged. I'd encourage you to write some tests too.

2024-11-19 05:10 UTC, benjmnxu commented on backend/ohq/models.py
> +        return gettext("%(start)s to %(end)s") % {
it might be better to just use an f-string for this case. lmk if theres a specific reason u chose gettext.

2024-11-19 05:10 UTC, benjmnxu commented on backend/ohq/models.py
> +from django.utils.translation import gettext, gettext_lazy as _
not sure if we need to support translations.

2024-11-19 05:10 UTC, benjmnxu commented on backend/ohq/views.py
> +from django.utils.translation import gettext_lazy as _
not sure we need these imports

2024-11-19 05:10 UTC, benjmnxu commented on backend/ohq/permissions.py
> +                        if booking.user is not None: # Doesn’t allow a student to update user if someone already booked the slot
could just return booking.user is None

2024-11-19 05:10 UTC, benjmnxu commented on backend/ohq/views.py
> +    def create(self, request, *args, **kwargs):
are we only allowed to create bookings in chronological order? For example, if an occurrence is from 1-3pm and no other bookings existed, I would only be able to book a slot at 1pm. If someone had booked starting at 1pm, I would only be able to book a 1:30pm spot (assuming interval is 30mins).

2025-02-26 23:20 UTC, vcai122 commented on backend/ohq/models.py
> +    title = models.CharField(("title"), max_length=255, blank=True)
what is this ("title") thing, similar to on the other fields?

2025-02-26 23:20 UTC, vcai122 commented on backend/ohq/models.py
> +    class Meta:
does the default verbose names not work

2025-02-26 23:20 UTC, vcai122 commented on backend/ohq/models.py
> +    interval = models.IntegerField(("interval"), blank=True, null=True)
is interval supposed to represent the length of how long a student can book time for during this occurence? Should this be specified on the event then?

2025-02-26 23:20 UTC, vcai122 commented on backend/ohq/models.py
> +            booking_count = int(delta_minutes // self.interval)
I'm not a big fan of making booking objects automatically on save. I'm not totally against it since I see the value in just having the objects be there, but in some sense we are creating multiple sources of truths (obviously bad!!) --> i.e. we require the bookings to be synchronized with the interval field, hence why we are overriding save to make sure of this but this is generally kind of sus.

2025-02-26 23:20 UTC, vcai122 commented on backend/ohq/models.py
> +            booking_count = int(delta_minutes // self.interval)
For example maybe one way to avoid this is to initially have no bookings and allow users to create bookings, but you validate the time they specified (valid times can be derived from the start time and interval fields)

2025-02-26 23:20 UTC, vcai122 commented on backend/ohq/models.py
> +            booking_count = int(delta_minutes // self.interval)
Also not sure how events fit into the picture

2025-02-26 23:20 UTC, vcai122 commented on backend/ohq/models.py
> +            booking_count = int(delta_minutes // self.interval)
Lets talk next time I'm at gbm

2025-02-26 23:20 UTC, vcai122 commented on backend/ohq/models.py
> +    def __init__(self, *args, **kwargs):
i know you just copied it but why is this code like this

2025-02-26 23:20 UTC, vcai122 commented on backend/ohq/permissions.py
> +            if membership is not None:
Can we use guard clauses instead of `else return False`

2025-02-26 23:20 UTC, vcai122 commented on backend/ohq/permissions.py
> +                else:
no need for else if you already returned True. A good heuristic for readable code is minimize indents

2025-02-26 23:20 UTC, vcai122 commented on backend/ohq/permissions.py
> +
maybe something like `if any(restricted_field in updated_fields for restricted_field in restricted_fields): return False`.

More readable since you can just read it like english

2025-02-26 23:20 UTC, vcai122 commented on backend/ohq/permissions.py
> +class BookingPermission(permissions.BasePermission):
seems like you're always doing occurence.event so why not make this get_membership_from_occurence? also this is better as a static function

2025-03-30 17:36 UTC, joyliu-q reviewed
Would prefer if a backend looked at this but top level looks good to me.

2025-03-30 17:36 UTC, joyliu-q commented on backend/ohq/migrations/0021_occurrence.py
Can these be collapsed to one migration file?

2025-03-30 17:36 UTC, joyliu-q commented on backend/ohq/models.py
> +
Can we document this behavior somewhere (either top level in code, in PR description, etc)

Also looping in @ryantanen who will likely be doing the frontend. If we are not allowing non-15-min intervals, we should also prevent booking non-15-min slots on the frontend as well.

2025-03-30 18:50 UTC, minghansun1 reviewed
LGTM except the one comment i added

2025-03-30 18:50 UTC, minghansun1 commented on backend/ohq/models.py
> +        if self.start.minute % 15 != 0:
If start time needs to be in 15 minute intervals, should end time also be in 15 minute intervals? Otherwise there may be un-utilized time between the end of a booking and the start of the next one

2025-03-30 19:02 UTC, joyliu-q approved these changes
Looks good to me!

2025-03-30 19:02 UTC, merged