Notifications
pennlabs/office-hours-queue pull request #37
Opened 2020-09-26 00:41 UTC by gautamr6

- Abstracted notification sound hook
- Instructors can now toggle notifications with button

2020-10-01 19:13 UTC, eyingxuan requested changes
In general, great first PR!! Hook is abstracted well and it'll be super easy to add audio players now!

Left some comments, and most of them are just nits about px to rem. After you make changes let's test it one more time and we can merge. 

Congrats on first PR @ OHQ 🎊🥳

2020-10-01 19:13 UTC, eyingxuan commented on frontend/components/Course/InstructorQueuePage/Queue.tsx
> +    // const play = usePlayer(bellAudio);
Remember to remove this comment!

2020-10-01 19:13 UTC, eyingxuan commented on frontend/pages/courses/[course]/index.tsx
> +                            <div style={{ marginTop: "-30px" }}>
Same nit about rem

2020-10-01 19:13 UTC, eyingxuan commented on frontend/hooks/player.ts
> +    const [player, setPlayer] = useState<UIfx | undefined>();
I know I used useState to begin with, but could you change this to a ref? It will save one unnecessary render

2020-10-01 19:13 UTC, eyingxuan commented on frontend/components/Course/StudentQueuePage/QuestionCard.tsx
> +    }, [question.status]);
ESLint is actually right on this one, you shouldn't disable it, and should add "play" to the dependency array. Remember that play() actually depends on notif, so right now if notif changes play() doesn't get updated properly here and might be stale.

2020-10-01 19:13 UTC, eyingxuan commented on frontend/components/Course/StudentQueuePage/QuestionCard.tsx
> +        if (question.status == QuestionStatus.ACTIVE) {
Use "===" for better style, in fact this should probably be a lint error instead of warning

2020-10-01 20:13 UTC, eyingxuan commented
Can you also add a screenshot to the PR for posteriority?

2020-10-10 16:43 UTC, gautamr6 commented
<img width="1792" alt="notifs on" src="https://user-images.githubusercontent.com/8990493/95660480-34dc0880-0af6-11eb-96fb-7479f6eae87e.png">
<img width="1792" alt="notifs off" src="https://user-images.githubusercontent.com/8990493/95660481-35749f00-0af6-11eb-970b-db6d9c9362e0.png">

2020-10-10 18:49 UTC, eyingxuan approved these changes
A couple of small things left, but looks good to (squash and) merge!

2020-10-10 18:49 UTC, eyingxuan commented on frontend/hooks/player.ts
> +    useEffect(() => {
This should have an empty dependency array so you don't create a new UIfx every time

2020-10-10 18:49 UTC, eyingxuan commented on frontend/hooks/player.ts
> +    const play = useRef<() => void>();
You can instantiate the function by passing it as a parameter to useRef - this makes sure that play.current is never undefined, and you don't have to do the check everywhere else

2020-10-10 18:50 UTC, eyingxuan commented on frontend/hooks/player.ts
> +    const play = useRef<() => void>();
Remember to also change the types elsewhere so you don't have to do play.current checks anymore

2020-10-10 20:13 UTC, merged